# Kibana is served by a back end server. This controls which port to use.
server.port: 5601

elasticsearch.url: "https://localhost:9200"

shield.encryptionKey: 02965ab9f37c4f7dbdff14a310fcc45c
shield.cookieName: tekstack-kibana
shield.clientId: KibanaApp
shield.clientSecret: KibanaAppSecret
#30 min
shield.sessionTimeout: 1800000
shield.url: "http://localhost:8080/oauth/token"
shield.userUrl: "http://localhost/api/users/search/current?projection=authorities"
shield.isSecure: false
shield.user: kibanaro
shield.password: tPaUET6AYzdRxBbLy9PH

# If you are running kibana behind a proxy, and want to mount it at a path,
# specify that path here. The basePath can't end in a slash.
server.basePath: ""

# Kibana uses an index in Elasticsearch to store saved searches, visualizations
# and dashboards. It will create a new index if it doesn't already exist.
kibana.index: "kibana"

# The default application to load.
kibana.defaultAppId: "discover"
kibana.loadApps: false

# If your Elasticsearch is protected with basic auth, these are the user credentials
# used by the Kibana server to perform maintenance on the kibana_index at startup. Your Kibana
# users will still need to authenticate with Elasticsearch (which is proxied through
# the Kibana server)
elasticsearch.username: "kibanaserver"
elasticsearch.password: "c7edzfdK3anA4cGnFCAJ"

# If you need to provide a CA certificate for your Elasticsearch instance, put
# the path of the pem file here.
# place the file in config dir
elasticsearch.ssl.ca: chain-ca.pem

# Set to false to have a complete disregard for the validity of the SSL
# certificate.
elasticsearch.ssl.verify: false

# Sense config - only for local dev
sense.proxyConfig:
  - match:
      host: "*" # allow any host that ends in .internal.org
      port: "{9200..9299}" # allow any port from 9200-9299
    ssl:
      ca: chain-ca.pem
  - match:
      protocol: "https"

    ssl:
      verify: false # allows any certificate to be used, even self-signed certs
  # since this rule has no "match" section it matches everything
  - timeout: 180000 # 3 minutes
